### ISSUE TITLE
Does not support FIPS compliance and actually breaks NPM

### ISSUE THREAD

**Issue by ayohrling** [npm/write-file-atomic#6]
When NodeJS is compiled for FIPS-compliance, write-file-atomic actually breaks NPM. 

When NPM attempts to write the local cache file .cache.json using writeFile from the library, it throws the following:

fips_md.c(146): OpenSSL internal error, assertion failed: Digest update previous FIPS forbidden algorithm error ignored
Aborted

Instead of hardcoding md5 hash for the temporary name, consider moving to something higher like sha1 at a minimum or check for FIPs compliance and make it variable. I tested by moving the function createhash() call to sha1 and it proceeds fine.

**Comment by stefanmb** [comment]
@ayohrling Should be resolved in https://github.com/iarna/write-file-atomic/pull/7.

**Comment by othiym23** [comment]
This is fixed by 22dd8759076fc8d0327d50693283060e479afafc, which was landed in lieu of #7 because of my poor reading comprehension skills (sorry again, @stefanmb). `npm@3.5.2` (currently `npm@next`) includes the fixed version of `write-file-atomic`, and should work with FIPS builds of Node.js. Thanks for the heads up!
